version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mixmate
      POSTGRES_USER: mixmateuser
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  api:
    build:
      context: .
      dockerfile: MixMate.API/Dockerfile
    ports:
      - "5165:5165"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__PostgresConnection=Host=postgres;Port=5432;Database=mixmate;Username=mixmateuser;Password=yourpassword

volumes:
  postgres_data: